name: android_world
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates
  - libffi=3.4.4
  - libzlib
  - ncurses=6.5
  - openssl
  - pip
  - python=3.11.8
  - readline=8.3
  - setuptools
  - sqlite
  - tk=8.6.15
  - wheel
  - xz=5.6.4
  - zlib
  - pip:
      - absl-py==2.1.0
      - android-env==1.2.3
      - android-world==0.1.0
      - annotated-types==0.7.0
      - anthropic==0.75.0
      - anyio==4.12.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - cachetools==6.2.4
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - decorator==5.2.1
      - distro==1.9.0
      - dm-env==1.6
      - dm-tree==0.1.9
      - docstring-parser==0.17.0
      - executing==2.2.1
      - filelock==3.20.1
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - fuzzywuzzy==0.18.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.45.0
      - google-auth-httplib2==0.3.0
      - google-generativeai==0.8.6
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - grpcio-tools==1.71.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - immutabledict==2.0.0
      - iniconfig==2.3.0
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jiter==0.12.0
      - jsonschema==4.17.3
      - kiwisolver==1.4.9
      - levenshtein==0.27.3
      - matplotlib==3.6.1
      - matplotlib-inline==0.2.1
      - numpy==1.26.3
      - openai==2.14.0
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.1.4
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - pluggy==1.6.0
      - portpicker==1.6.0
      - prompt-toolkit==3.0.52
      - proto-plus==1.27.0
      - protobuf==5.29.5
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygame==2.6.1
      - pygments==2.19.2
      - pyparsing==3.3.1
      - pyrsistent==0.20.0
      - pysqlite3==0.5.4
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - python-levenshtein==0.27.3
      - pytz==2025.2
      - pyyaml==6.0.3
      - rapidfuzz==3.14.3
      - regex==2025.11.3
      - requests==2.32.5
      - rsa==4.9.1
      - safetensors==0.7.0
      - six==1.17.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - tenacity==9.1.2
      - termcolor==3.3.0
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uritemplate==4.2.0
      - urllib3==2.6.2
      - wcwidth==0.2.14
      - wrapt==2.0.1
prefix: /opt/miniconda3/envs/android_world
